//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchEngine.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SearchEngineEntities : DbContext
    {
        public SearchEngineEntities()
            : base("name=SearchEngineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Books> Books { get; set; }
        public DbSet<Categories> Categories { get; set; }
        public DbSet<Publishers> Publishers { get; set; }
        public DbSet<SearchDetail> SearchDetail { get; set; }
        public DbSet<KeyWordsRank> KeyWordsRank { get; set; }
        public DbSet<Admin> Admin { get; set; }
    }
}
